# Generated by Django 5.1.6 on 2025-02-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=7)),
                ('type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], default='car', max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('Color', models.CharField(max_length=255)),
            ],
        ),
    ]
