# Generated by Django 5.1.6 on 2025-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'occupied')], default='available', max_length=255)),
                ('type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], default='car', max_length=255)),
                ('number_spaces', models.PositiveIntegerField()),
            ],
        ),
    ]
